#pragma once
#define LSPO_KEY KC_8
#define RSPC_KEY KC_9
#define LCPO_KEYS KC_LCTL, KC_RALT, KC_7
#define RCPC_KEYS KC_RCTL, KC_RALT, KC_0
#define LAPO_KEYS KC_LALT, KC_RALT, KC_8
#define RAPC_KEYS KC_RALT, KC_RALT, KC_9
